package com.mycompany.studentsystem;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
public class StudentInformationSystem extends javax.swing.JFrame {
    private DefaultListModel<String> studentListModel;
    /**
     * Creates new form StudentInformationSystem
     */
    public StudentInformationSystem() {
        initComponents();
        initListeners();
        
        studentListModel = new DefaultListModel<>();
        jlistStudent.setModel(studentListModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     private void initListeners() {
        //Save Button//
        jbSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Get user input from text fields
                String id = txtID.getText();
                String name = txtName.getText();
                String course = txtCourse.getText();
                String ageText = txtAge.getText();
                String address = txtAddress.getText();
                String gpaText = txtGpa.getText();

                try {
                    int age = Integer.parseInt(ageText);
                    if (age <= 0) {
                        throw new IllegalArgumentException("Age must be a Positive number greater than zero.");
                    }

                    double gpa = Double.parseDouble(gpaText);
                    if (gpa < 1.0 || gpa > 5.0) { 
                        throw new IllegalArgumentException("GPA must be a number between 1.0 and 5.0");
                    }


                    jlOutputId.setText(id);
                    jlOutputName.setText(name);
                    jlOutputCourse.setText(course);
                    jlOutputAge.setText(ageText);
                    jlOutputAddress.setText(address);
                    jlOutputGpa.setText(gpaText);


                    studentListModel.addElement(name + " - " + course);

                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null,
                        "Please enter valid number for Age and GPA.",
                        "Input Error",
                        JOptionPane.ERROR_MESSAGE);
                } catch (IllegalArgumentException ex) {

                    JOptionPane.showMessageDialog(null,
                        ex.getMessage(), 
                        "Validation Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        //Clear Button//
        jbClear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                txtID.setText("");
                txtName.setText("");
                txtCourse.setText("");
                txtAge.setText("");
                txtAddress.setText("");
                txtGpa.setText("");
                
                jlOutputId.setText("");
                jlOutputName.setText("");
                jlOutputCourse.setText("");
                jlOutputAge.setText("");
                jlOutputAddress.setText("");
                jlOutputGpa.setText("");
            }
        });
        
        //Remove Button bai//
        jbRemove.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = jlistStudent.getSelectedIndex();
                if (selectedIndex != -1) {
                    studentListModel.remove(selectedIndex); 
                }
            }
        });
          
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlID = new javax.swing.JLabel();
        jlName = new javax.swing.JLabel();
        jlCourse = new javax.swing.JLabel();
        jlAge = new javax.swing.JLabel();
        jlAddress = new javax.swing.JLabel();
        jlGpa = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtCourse = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtGpa = new javax.swing.JTextField();
        jbSave = new javax.swing.JButton();
        jbClear = new javax.swing.JButton();
        jbRemove = new javax.swing.JButton();
        jlHeader = new javax.swing.JLabel();
        jlOutID = new javax.swing.JLabel();
        jlOutName = new javax.swing.JLabel();
        jlOutCourse = new javax.swing.JLabel();
        jlOutAge = new javax.swing.JLabel();
        jlOutAddress = new javax.swing.JLabel();
        jlOutGpa = new javax.swing.JLabel();
        jlpanelHeader = new javax.swing.JLabel();
        jlOutputId = new javax.swing.JLabel();
        jlOutputName = new javax.swing.JLabel();
        jlOutputCourse = new javax.swing.JLabel();
        jlOutputAge = new javax.swing.JLabel();
        jlOutputAddress = new javax.swing.JLabel();
        jlOutputGpa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistStudent = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlID.setText("Student ID");

        jlName.setText("Student Name");

        jlCourse.setText("Course");

        jlAge.setText("Age");

        jlAddress.setText("Address");

        jlGpa.setText("GPA");

        txtAge.setToolTipText("");

        jbSave.setText("Save");

        jbClear.setText("Clear");

        jbRemove.setText("Remove");

        jlHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlHeader.setText("STUDENT INFORMATION DETAILS");

        jlOutID.setText("Student ID");

        jlOutName.setText("Student Name");

        jlOutCourse.setText("Course");

        jlOutAge.setText("Age");

        jlOutAddress.setText("Address");

        jlOutGpa.setText("GPA");

        jlpanelHeader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlpanelHeader.setText("STUDENT LIST");

        jScrollPane1.setViewportView(jlistStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jbSave)
                        .addGap(18, 18, 18)
                        .addComponent(jbClear)
                        .addGap(18, 18, 18)
                        .addComponent(jbRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlID)
                            .addComponent(jlName)
                            .addComponent(jlCourse)
                            .addComponent(jlAge)
                            .addComponent(jlAddress)
                            .addComponent(jlGpa))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtName)
                            .addComponent(txtCourse)
                            .addComponent(txtAge)
                            .addComponent(txtAddress)
                            .addComponent(txtGpa, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlpanelHeader)
                            .addComponent(jlOutputId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOutputName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOutputCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOutputAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOutputAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOutputGpa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlOutName)
                                    .addComponent(jlOutID)
                                    .addComponent(jlOutCourse)
                                    .addComponent(jlOutAge)
                                    .addComponent(jlOutAddress)
                                    .addComponent(jlOutGpa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(56, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlHeader)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutID)
                    .addComponent(jlOutputId))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutName)
                    .addComponent(jlOutputName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCourse)
                    .addComponent(txtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutCourse)
                    .addComponent(jlOutputCourse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutAge)
                    .addComponent(jlOutputAge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutAddress)
                    .addComponent(jlOutputAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGpa)
                    .addComponent(txtGpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOutGpa)
                    .addComponent(jlOutputGpa))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSave)
                            .addComponent(jbClear)
                            .addComponent(jbRemove))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jlpanelHeader)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInformationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInformationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInformationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentInformationSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbClear;
    private javax.swing.JButton jbRemove;
    private javax.swing.JButton jbSave;
    private javax.swing.JLabel jlAddress;
    private javax.swing.JLabel jlAge;
    private javax.swing.JLabel jlCourse;
    private javax.swing.JLabel jlGpa;
    private javax.swing.JLabel jlHeader;
    private javax.swing.JLabel jlID;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlOutAddress;
    private javax.swing.JLabel jlOutAge;
    private javax.swing.JLabel jlOutCourse;
    private javax.swing.JLabel jlOutGpa;
    private javax.swing.JLabel jlOutID;
    private javax.swing.JLabel jlOutName;
    private javax.swing.JLabel jlOutputAddress;
    private javax.swing.JLabel jlOutputAge;
    private javax.swing.JLabel jlOutputCourse;
    private javax.swing.JLabel jlOutputGpa;
    private javax.swing.JLabel jlOutputId;
    private javax.swing.JLabel jlOutputName;
    private javax.swing.JList<String> jlistStudent;
    private javax.swing.JLabel jlpanelHeader;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCourse;
    private javax.swing.JTextField txtGpa;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
